import type { ActivityEvent } from "@/lib/types/activityEvents";

export const MOCK_ACTIVITY_FEED: ActivityEvent[] = [
  /* ── Aujourd'hui ─────────────────────────────────────── */
  {
    id: "evt-001",
    type: "coach_replied",
    priority: 1,
    direction: "inbound",
    athleteId: "ath-001",
    athleteName: "Marc-Antoine Tremblay",
    athletePosition: "QB",
    coachId: "coach-001",
    coachName: "Coach Bergeron",
    message: "{coach} a répondu à ton message concernant {athlete}.",
    icon: "message-circle",
    iconColor: "#22C55E",
    actionLabel: "Voir la conversation",
    actionUrl: "/recruteur/messages/thread-001",
    timestamp: "2026-03-11T09:15:00",
    relativeTime: "Il y a 45 min",
    timeGroup: "Aujourd'hui",
    metadata: { threadId: "thread-001" },
  },
  {
    id: "evt-002",
    type: "competitor_favorited",
    priority: 1,
    direction: "inbound",
    athleteId: "ath-002",
    athleteName: "Jérémy Lavoie",
    athletePosition: "WR",
    message: "{athlete} a été ajouté aux favoris par 5 recruteurs cette semaine.",
    icon: "heart",
    iconColor: "#E63946",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-002",
    timestamp: "2026-03-11T08:30:00",
    relativeTime: "Il y a 1h30",
    timeGroup: "Aujourd'hui",
    metadata: { favCount: 5 },
  },
  {
    id: "evt-003",
    type: "video_added",
    priority: 1,
    direction: "inbound",
    athleteId: "ath-003",
    athleteName: "Félix Gagnon-Roy",
    athletePosition: "RB",
    message: "{athlete} a ajouté une nouvelle vidéo highlights.",
    icon: "film",
    iconColor: "#22C55E",
    actionLabel: "Regarder la vidéo",
    actionUrl: "/recruteur/athletes/ath-003",
    timestamp: "2026-03-11T07:45:00",
    relativeTime: "Il y a 2h",
    timeGroup: "Aujourd'hui",
  },

  /* ── Hier ─────────────────────────────────────────────── */
  {
    id: "evt-004",
    type: "badge_added",
    priority: 2,
    direction: "inbound",
    athleteId: "ath-003",
    athleteName: "Félix Gagnon-Roy",
    athletePosition: "RB",
    message: "{athlete} a reçu le badge Capitaine.",
    icon: "award",
    iconColor: "#F59E0B",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-003",
    timestamp: "2026-03-10T16:00:00",
    relativeTime: "Hier, 16h",
    timeGroup: "Hier",
    metadata: { badgeName: "Capitaine", badgeIcon: "award" },
  },
  {
    id: "evt-005",
    type: "profile_verified",
    priority: 2,
    direction: "inbound",
    athleteId: "ath-004",
    athleteName: "William Pelletier",
    athletePosition: "OL",
    message: "{athlete} est maintenant un profil vérifié.",
    icon: "check-circle",
    iconColor: "#3B82F6",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-004",
    timestamp: "2026-03-10T14:30:00",
    relativeTime: "Hier, 14h30",
    timeGroup: "Hier",
  },
  {
    id: "evt-006",
    type: "scouting_report_updated",
    priority: 2,
    direction: "inbound",
    athleteId: "ath-001",
    athleteName: "Marc-Antoine Tremblay",
    athletePosition: "QB",
    message: "Le rapport de dépistage de {athlete} a été mis à jour.",
    icon: "file-text",
    iconColor: "#F59E0B",
    actionLabel: "Lire le rapport",
    actionUrl: "/recruteur/athletes/ath-001",
    timestamp: "2026-03-10T11:00:00",
    relativeTime: "Hier, 11h",
    timeGroup: "Hier",
  },
  {
    id: "evt-007",
    type: "new_athlete",
    priority: 2,
    direction: "inbound",
    athleteId: "ath-005",
    athleteName: "Gabriel Morin",
    athletePosition: "LB",
    message: "{athlete} (LB) a été ajouté à la plateforme.",
    icon: "user-plus",
    iconColor: "#22C55E",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-005",
    timestamp: "2026-03-10T09:00:00",
    relativeTime: "Hier, 9h",
    timeGroup: "Hier",
  },

  /* ── Cette semaine (Lundi) ────────────────────────────── */
  {
    id: "evt-008",
    type: "status_visite",
    priority: 2,
    direction: "outbound",
    athleteId: "ath-006",
    athleteName: "Xavier Lapointe",
    athletePosition: "DB",
    message: "Visite planifiée pour {athlete} le 22 mars.",
    icon: "calendar",
    iconColor: "#E63946",
    actionLabel: "Voir les détails",
    actionUrl: "/recruteur/athletes/ath-006",
    timestamp: "2026-03-09T15:00:00",
    relativeTime: "Lundi",
    timeGroup: "Cette semaine",
    metadata: { visitDate: "2026-03-22" },
  },
  {
    id: "evt-009",
    type: "status_engage",
    priority: 2,
    direction: "outbound",
    athleteId: "ath-007",
    athleteName: "Thomas Carrier-Brault",
    athletePosition: "DL",
    message: "{athlete} est maintenant marqué comme Engagé.",
    icon: "handshake",
    iconColor: "#E63946",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-007",
    timestamp: "2026-03-09T10:00:00",
    relativeTime: "Lundi",
    timeGroup: "Cette semaine",
  },

  /* ── Cette semaine (Vendredi) ─────────────────────────── */
  {
    id: "evt-010",
    type: "status_lettre_signee",
    priority: 1,
    direction: "outbound",
    athleteId: "ath-007",
    athleteName: "Thomas Carrier-Brault",
    athletePosition: "DL",
    message: "{athlete} a signé sa lettre d'intention!",
    icon: "pen-tool",
    iconColor: "#E63946",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-007",
    timestamp: "2026-03-06T14:00:00",
    relativeTime: "Vendredi",
    timeGroup: "Cette semaine",
  },
  {
    id: "evt-011",
    type: "recruiter_sent_message",
    priority: 3,
    direction: "outbound",
    athleteId: "ath-003",
    athleteName: "Félix Gagnon-Roy",
    athletePosition: "RB",
    message: "Tu as envoyé un message au coach de {athlete}.",
    icon: "send",
    iconColor: "#6B7280",
    actionLabel: "Voir le message",
    actionUrl: "/recruteur/messages/thread-003",
    timestamp: "2026-03-06T11:00:00",
    relativeTime: "Vendredi",
    timeGroup: "Cette semaine",
    metadata: { threadId: "thread-003" },
  },
  {
    id: "evt-012",
    type: "recruiter_favorited",
    priority: 3,
    direction: "outbound",
    athleteId: "ath-008",
    athleteName: "Samuel Côté",
    athletePosition: "K",
    message: "Tu as ajouté {athlete} à tes favoris.",
    icon: "heart",
    iconColor: "#6B7280",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-008",
    timestamp: "2026-03-06T09:30:00",
    relativeTime: "Vendredi",
    timeGroup: "Cette semaine",
  },

  /* ── Semaine dernière (Jeudi) ─────────────────────────── */
  {
    id: "evt-013",
    type: "physical_updated",
    priority: 3,
    direction: "inbound",
    athleteId: "ath-009",
    athleteName: "Mathis Dufresne",
    athletePosition: "TE",
    message: "Les données physiques de {athlete} ont été mises à jour.",
    icon: "bar-chart-3",
    iconColor: "#6B7280",
    actionLabel: "Voir les stats",
    actionUrl: "/recruteur/athletes/ath-009",
    timestamp: "2026-03-05T13:00:00",
    relativeTime: "Jeudi dernier",
    timeGroup: "Semaine dernière",
  },
  {
    id: "evt-014",
    type: "photo_added",
    priority: 3,
    direction: "inbound",
    athleteId: "ath-006",
    athleteName: "Xavier Lapointe",
    athletePosition: "DB",
    message: "{athlete} a ajouté une nouvelle photo de profil.",
    icon: "camera",
    iconColor: "#6B7280",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-006",
    timestamp: "2026-03-05T10:00:00",
    relativeTime: "Jeudi dernier",
    timeGroup: "Semaine dernière",
  },

  /* ── Semaine dernière (Mercredi) ──────────────────────── */
  {
    id: "evt-015",
    type: "status_retire",
    priority: 3,
    direction: "outbound",
    athleteId: "ath-010",
    athleteName: "Noah Simard",
    athletePosition: "S",
    message: "{athlete} a été retiré de ta liste de suivi.",
    icon: "x-circle",
    iconColor: "#6B7280",
    actionLabel: "Voir le profil",
    actionUrl: "/recruteur/athletes/ath-010",
    timestamp: "2026-03-04T16:00:00",
    relativeTime: "Mercredi dernier",
    timeGroup: "Semaine dernière",
    metadata: { retireReason: "Pas le bon fit" },
  },
];
