-- FEEP Private Secondary Schools - Complete list from feep.qc.ca
-- 146 schools filtered by Secondary School education level
-- Type: SECONDAIRE (matches existing public schools)

INSERT INTO schools (name, type, city) VALUES
('Académie Antoine-Manseau', 'SECONDAIRE', 'Joliette'),
('Académie Chrétienne Rive-Nord', 'SECONDAIRE', 'Laval'),
('Académie Culturelle de Laval', 'SECONDAIRE', 'Laval'),
('Académie Ibn Sina', 'SECONDAIRE', 'Montréal'),
('Académie Lafontaine', 'SECONDAIRE', 'Saint-Jérôme'),
('Académie Marie-Laurier', 'SECONDAIRE', 'Brossard'),
('Académie Michèle-Provost', 'SECONDAIRE', 'Montréal'),
('Académie Saint-Louis', 'SECONDAIRE', 'Québec'),
('Académie Ste-Thérèse', 'SECONDAIRE', 'Sainte-Thérèse'),
('Bishop''s College School', 'SECONDAIRE', 'Sherbrooke'),
('Centennial Academy', 'SECONDAIRE', 'Montréal'),
('Centre académique Fournier', 'SECONDAIRE', 'Montréal'),
('Centre d''intégration scolaire', 'SECONDAIRE', 'Montréal'),
('Centre François-Michelle', 'SECONDAIRE', 'Montréal'),
('Collège Beaubois', 'SECONDAIRE', 'Montréal'),
('Collège Boisbriand', 'SECONDAIRE', 'Boisbriand'),
('Collège Bourget', 'SECONDAIRE', 'Rigaud'),
('Collège Champagneur', 'SECONDAIRE', 'Rawdon'),
('Collège Charlemagne', 'SECONDAIRE', 'Montréal'),
('Collège Charles-Lemoyne (Sainte-Catherine)', 'SECONDAIRE', 'Sainte-Catherine'),
('Collège Charles-Lemoyne (Longueuil)', 'SECONDAIRE', 'Longueuil'),
('Collège Citoyen', 'SECONDAIRE', 'Laval'),
('Collège Clarétain de Victoriaville', 'SECONDAIRE', 'Victoriaville'),
('Collège d''Anjou', 'SECONDAIRE', 'Montréal'),
('Collège de Champigny', 'SECONDAIRE', 'Québec'),
('Collège de l''Assomption', 'SECONDAIRE', 'L''Assomption'),
('Collège de Lévis', 'SECONDAIRE', 'Lévis'),
('Collège de Montréal', 'SECONDAIRE', 'Montréal'),
('Collège de Sainte-Anne-de-la-Pocatière', 'SECONDAIRE', 'La Pocatière'),
('Collège des Hauts Sommets', 'SECONDAIRE', 'Saint-Tite-des-Caps'),
('Collège du Mont-Sainte-Anne', 'SECONDAIRE', 'Sherbrooke'),
('Collège Durocher Saint-Lambert', 'SECONDAIRE', 'Saint-Lambert'),
('Collège Esther-Blondin', 'SECONDAIRE', 'Saint-Jacques'),
('Collège Français Secondaire Longueuil', 'SECONDAIRE', 'Longueuil'),
('Collège Français Secondaire Montréal', 'SECONDAIRE', 'Montréal'),
('Collège François-de-Laval', 'SECONDAIRE', 'Québec'),
('Collège François-Delaplace', 'SECONDAIRE', 'Waterville'),
('Collège Héritage de Châteauguay', 'SECONDAIRE', 'Châteauguay'),
('Collège international Marie de France', 'SECONDAIRE', 'Montréal'),
('Collège Jean de la Mennais', 'SECONDAIRE', 'La Prairie'),
('Collège Jean-de-Brébeuf', 'SECONDAIRE', 'Montréal'),
('Collège Jean-Eudes', 'SECONDAIRE', 'Montréal'),
('Collège Jésus-Marie de Bellechasse', 'SECONDAIRE', 'Sainte-Sabine'),
('Collège Jésus-Marie de Sillery', 'SECONDAIRE', 'Québec'),
('Collège Laurentien', 'SECONDAIRE', 'Val-Morin'),
('Collège Laval', 'SECONDAIRE', 'Laval'),
('Collège Letendre', 'SECONDAIRE', 'Laval'),
('Collège Marie-de-l''Incarnation', 'SECONDAIRE', 'Trois-Rivières'),
('Collège mariste de Québec', 'SECONDAIRE', 'Québec'),
('Collège Mont Notre-Dame de Sherbrooke', 'SECONDAIRE', 'Sherbrooke'),
('Collège Mont-Royal', 'SECONDAIRE', 'Montréal'),
('Collège Mont-Sacré-Coeur', 'SECONDAIRE', 'Granby'),
('Collège Mont-Saint-Louis', 'SECONDAIRE', 'Montréal'),
('Collège Notre-Dame', 'SECONDAIRE', 'Montréal'),
('Collège Notre-Dame de Rivière-du-Loup', 'SECONDAIRE', 'Rivière-du-Loup'),
('Collège Notre-Dame-de-l''Assomption', 'SECONDAIRE', 'Nicolet'),
('Collège Notre-Dame-de-Lourdes', 'SECONDAIRE', 'Longueuil'),
('Collège Nouvelles Frontières', 'SECONDAIRE', 'Gatineau'),
('Collège Pasteur', 'SECONDAIRE', 'Montréal'),
('Collège Regina Assumpta', 'SECONDAIRE', 'Montréal'),
('Collège Reine-Marie', 'SECONDAIRE', 'Montréal'),
('Collège Rivier', 'SECONDAIRE', 'Coaticook'),
('Collège Saint-Alexandre', 'SECONDAIRE', 'Gatineau'),
('Collège Saint-Bernard', 'SECONDAIRE', 'Drummondville'),
('Collège Saint-Charles-Garnier', 'SECONDAIRE', 'Québec'),
('Collège Saint-Hilaire', 'SECONDAIRE', 'Mont-Saint-Hilaire'),
('Collège Saint-Joseph de Hull', 'SECONDAIRE', 'Gatineau'),
('Collège Saint-Maurice', 'SECONDAIRE', 'Saint-Hyacinthe'),
('Collège Saint-Paul', 'SECONDAIRE', 'Varennes'),
('Collège Saint-Sacrement', 'SECONDAIRE', 'Terrebonne'),
('Collège Sainte-Anne', 'SECONDAIRE', 'Montréal'),
('Collège Sainte-Anne (Dorval)', 'SECONDAIRE', 'Dorval'),
('Collège Sainte-Marcelline', 'SECONDAIRE', 'Montréal'),
('Collège St-Jean-Vianney', 'SECONDAIRE', 'Montréal'),
('Collège Stanislas (Montréal)', 'SECONDAIRE', 'Montréal'),
('Collège Stanislas (Québec)', 'SECONDAIRE', 'Québec'),
('Collège Stanstead', 'SECONDAIRE', 'Stanstead'),
('Collège Trafalgar', 'SECONDAIRE', 'Montréal'),
('Collège Trinité', 'SECONDAIRE', 'Saint-Bruno-de-Montarville'),
('Collège Ville-Marie', 'SECONDAIRE', 'Montréal'),
('École À Pas de Géant', 'SECONDAIRE', 'Montréal'),
('École Al-Houda', 'SECONDAIRE', 'Montréal'),
('École Alex Manoogian', 'SECONDAIRE', 'Montréal'),
('École Ali Ibn Abi Talib', 'SECONDAIRE', 'Montréal'),
('École de la Synergie', 'SECONDAIRE', 'Montréal'),
('École Félix-Antoine', 'SECONDAIRE', 'Montréal'),
('École Jésus-Marie de Beauceville', 'SECONDAIRE', 'Beauceville'),
('École JMC', 'SECONDAIRE', 'Montréal'),
('École LE REPAIRE', 'SECONDAIRE', 'Beloeil'),
('École Le Savoir', 'SECONDAIRE', 'Montréal'),
('École Le Sommet - Summit School', 'SECONDAIRE', 'Montréal'),
('École Les Trois Saisons', 'SECONDAIRE', 'Boucherville'),
('École Lucien-Guilbault (Papineau)', 'SECONDAIRE', 'Montréal'),
('École Lucien-Guilbault', 'SECONDAIRE', 'Montréal'),
('École Maïmonide', 'SECONDAIRE', 'Montréal'),
('École Marcelle-Mallet', 'SECONDAIRE', 'Lévis'),
('École Marie-Clarac', 'SECONDAIRE', 'Montréal'),
('École Miss Edgar et Miss Cramp', 'SECONDAIRE', 'Westmount'),
('École Montessori Orford', 'SECONDAIRE', 'Orford'),
('École nationale de cirque', 'SECONDAIRE', 'Montréal'),
('École Notre-Dame de Nareg', 'SECONDAIRE', 'Laval'),
('École oraliste de Québec', 'SECONDAIRE', 'Québec'),
('École Peter Hall', 'SECONDAIRE', 'Montréal'),
('École Rudolf Steiner de Montréal', 'SECONDAIRE', 'Montréal'),
('École secondaire de Bromptonville', 'SECONDAIRE', 'Sherbrooke'),
('École secondaire du Verbe Divin', 'SECONDAIRE', 'Granby'),
('École secondaire Duval', 'SECONDAIRE', 'Montréal'),
('École secondaire Loyola', 'SECONDAIRE', 'Montréal'),
('École secondaire Marcellin-Champagnat', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu'),
('École secondaire Mont-Saint-Sacrement', 'SECONDAIRE', 'Saint-Gabriel-de-Valcartier'),
('École secondaire privée François-Bourrin', 'SECONDAIRE', 'Québec'),
('École secondaire Saint-Joseph', 'SECONDAIRE', 'Saint-Hyacinthe'),
('École Socrates-Démosthène (Laval)', 'SECONDAIRE', 'Laval'),
('École Socrates-Démosthène (Montréal)', 'SECONDAIRE', 'Montréal'),
('École St-François', 'SECONDAIRE', 'Québec'),
('École Vanguard', 'SECONDAIRE', 'Montréal'),
('Édu2', 'SECONDAIRE', 'Montréal'),
('Étude Secours', 'SECONDAIRE', 'Trois-Rivières'),
('Externat Sacré-Coeur', 'SECONDAIRE', 'Rosemère'),
('Institut d''Enseignement de Sept-Îles', 'SECONDAIRE', 'Sept-Îles'),
('Institut Secondaire Keranna', 'SECONDAIRE', 'Trois-Rivières'),
('Juvénat Notre-Dame du Saint-Laurent', 'SECONDAIRE', 'Lévis'),
('L''Académie de la Vallée du Roy', 'SECONDAIRE', 'Lavaltrie'),
('L''École arménienne Sourp Hagop', 'SECONDAIRE', 'Montréal'),
('L''École L''Eau-Vive', 'SECONDAIRE', 'Québec'),
('L''École Selwyn House', 'SECONDAIRE', 'Westmount'),
('Le Salesien', 'SECONDAIRE', 'Sherbrooke'),
('Les écoles Azrieli Talmud Torah Herzliah', 'SECONDAIRE', 'Montréal'),
('Lower Canada College', 'SECONDAIRE', 'Montréal'),
('North Star Academy Laval', 'SECONDAIRE', 'Laval'),
('Pensionnat du Saint-Nom-de-Marie', 'SECONDAIRE', 'Montréal'),
('Résonance Montréal', 'SECONDAIRE', 'Westmount'),
('Saint-Jean-Eudes', 'SECONDAIRE', 'Québec'),
('Séminaire de Chicoutimi', 'SECONDAIRE', 'Saguenay'),
('Séminaire de Sherbrooke', 'SECONDAIRE', 'Sherbrooke'),
('Séminaire du Sacré-Coeur', 'SECONDAIRE', 'Nominingue'),
('Séminaire Marie-Reine-du-Clergé', 'SECONDAIRE', 'Métabetchouan-Lac-à-la-Croix'),
('Séminaire Saint-François', 'SECONDAIRE', 'Saint-Augustin-de-Desmaures'),
('Séminaire Saint-Joseph de Trois-Rivières', 'SECONDAIRE', 'Trois-Rivières'),
('Séminaire Sainte-Marie', 'SECONDAIRE', 'Shawinigan'),
('Succès scolaire', 'SECONDAIRE', 'Longueuil'),
('The Study', 'SECONDAIRE', 'Westmount'),
('Villa Maria', 'SECONDAIRE', 'Montréal'),
('Villa Sainte-Marcelline', 'SECONDAIRE', 'Westmount'),
('West Island College', 'SECONDAIRE', 'Dollard-des-Ormeaux')
ON CONFLICT DO NOTHING;
