-- Quebec school seed — generated 2026-04-13
-- Source: Donnees Quebec open data (public, private, collegial)

BEGIN;

-- New SECONDAIRE schools (686 rows)
INSERT INTO schools (id, name, type, city, region) VALUES
  (gen_random_uuid(), 'École Harrington', 'SECONDAIRE', 'Côte-Nord-du-Golfe-du-Saint-Laurent', 'Côte-Nord'),
  (gen_random_uuid(), 'École Mecatina', 'SECONDAIRE', 'Gros-Mécatina', 'Côte-Nord'),
  (gen_random_uuid(), 'École Kegaska', 'SECONDAIRE', 'Côte-Nord-du-Golfe-du-Saint-Laurent', 'Côte-Nord'),
  (gen_random_uuid(), 'École Saint-Augustine', 'SECONDAIRE', 'Saint-Augustin', 'Côte-Nord'),
  (gen_random_uuid(), 'École Saint-Paul', 'SECONDAIRE', 'Bonne-Espérance', 'Côte-Nord'),
  (gen_random_uuid(), 'École Monseigneur-Scheffer', 'SECONDAIRE', 'Blanc-Sablon', 'Côte-Nord'),
  (gen_random_uuid(), 'École Saint-Joseph', 'SECONDAIRE', 'L''Île-d''Anticosti', 'Côte-Nord'),
  (gen_random_uuid(), 'École Gabriel-Dionne', 'SECONDAIRE', 'Côte-Nord-du-Golfe-du-Saint-Laurent', 'Côte-Nord'),
  (gen_random_uuid(), 'École Netagamiou', 'SECONDAIRE', 'Côte-Nord-du-Golfe-du-Saint-Laurent', 'Côte-Nord'),
  (gen_random_uuid(), 'École Secondaire Armand-Saint-Onge', 'SECONDAIRE', 'Amqui', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Sayabec', 'SECONDAIRE', 'Sayabec', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Forimont', 'SECONDAIRE', 'Causapscal', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de l''Écho-des-Montagnes-Lavoie', 'SECONDAIRE', 'Saint-Fabien', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Paul-Hubert', 'SECONDAIRE', 'Rimouski', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École du Mistral', 'SECONDAIRE', 'Mont-Joli', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Sainte-Luce-des Bois-et-Marées', 'SECONDAIRE', 'Sainte-Luce', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Langevin-Saint-Jean', 'SECONDAIRE', 'Rimouski', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Mont-Saint-Louis-Saint-Rosaire', 'SECONDAIRE', 'Rimouski', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Grand Défi', 'SECONDAIRE', 'Mont-Joli', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Merisiers', 'SECONDAIRE', 'Rimouski', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Boijoli', 'SECONDAIRE', 'Saint-Narcisse-de-Rimouski', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Hauts-Plateaux', 'SECONDAIRE', 'Les Hauteurs', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Litalien', 'SECONDAIRE', 'Trois-Pistoles', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Litalien', 'SECONDAIRE', 'Saint-Mathieu-de-Rioux', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Gérard-Collin', 'SECONDAIRE', 'Témiscouata-sur-le-Lac', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École du Jall', 'SECONDAIRE', 'Saint-Juste-du-Lac', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École du Jall', 'SECONDAIRE', 'Lejeune', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École du Jall', 'SECONDAIRE', 'Auclair', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Chanoine-Côté', 'SECONDAIRE', 'Sainte-Françoise', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Chanoine-Côté', 'SECONDAIRE', 'Saint-Éloi', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École primaire de Dégelis', 'SECONDAIRE', 'Dégelis', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Jolis-Vents', 'SECONDAIRE', 'Saint-Cyprien', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Jolis-Vents', 'SECONDAIRE', 'Saint-Clément', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Jolis-Vents', 'SECONDAIRE', 'Sainte-Rita', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Saint-Jean-de-Dieu', 'SECONDAIRE', 'Trois-Pistoles', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Beaucourt - Saint-Eusèbe', 'SECONDAIRE', 'Packington', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École de Beaucourt - Saint-Eusèbe', 'SECONDAIRE', 'Saint-Eusèbe', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire de la Vallée-des-Lacs', 'SECONDAIRE', 'Saint-Michel-du-Squatec', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire de Dégelis', 'SECONDAIRE', 'Dégelis', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École primaire du Transcontinental', 'SECONDAIRE', 'Pohénégamook', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École primaire du Transcontinental', 'SECONDAIRE', 'Rivière-Bleue', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École primaire du Transcontinental', 'SECONDAIRE', 'Saint-Athanase', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Notre-Dame', 'SECONDAIRE', 'Témiscouata-sur-le-Lac', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Georges-Gauvin', 'SECONDAIRE', 'Saint-Louis-du-Ha! Ha!', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Georges-Gauvin', 'SECONDAIRE', 'Saint-Honoré-de-Témiscouata', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Georges-Gauvin', 'SECONDAIRE', 'Saint-Elzéar-de-Témiscouata', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École La Source', 'SECONDAIRE', 'Biencourt', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École La Source', 'SECONDAIRE', 'Lac-des-Aigles', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École La Source', 'SECONDAIRE', 'Saint-Michel-du-Squatec', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire de Cabano', 'SECONDAIRE', 'Témiscouata-sur-le-Lac', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire de Trois-Pistoles', 'SECONDAIRE', 'Trois-Pistoles', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire du Transcontinental', 'SECONDAIRE', 'Pohénégamook', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École des Vieux-Moulins et Saint-Modeste', 'SECONDAIRE', 'Saint-Hubert-de-Rivière-du-Loup', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École secondaire Chanoine-Beaudet', 'SECONDAIRE', 'Saint-Pascal', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École polyvalente La Pocatière', 'SECONDAIRE', 'La Pocatière', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'École Cité étudiante', 'SECONDAIRE', 'Roberval', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'Polyvalente des Quatre-Vents', 'SECONDAIRE', 'Saint-Félicien', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'Polyvalente de Normandin', 'SECONDAIRE', 'Normandin', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire des Grandes-Rivières', 'SECONDAIRE', 'Dolbeau-Mistassini', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire Camille-Lavoie', 'SECONDAIRE', 'Alma', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'Pavillon Wilbrod-Dufour', 'SECONDAIRE', 'Alma', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École Curé-Hébert', 'SECONDAIRE', 'Hébertville', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École Jean-Gauthier', 'SECONDAIRE', 'Alma', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire Charles-Gravel', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École primaire et secondaire Fréchette', 'SECONDAIRE', 'L''Anse-Saint-Jean', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire des Grandes-Marées', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire de l''Odyssée', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École polyvalente Arvida', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École secondaire des Bâtisseurs', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'Centre éducatif Saint-Aubin', 'SECONDAIRE', 'Baie-Saint-Paul', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire du Plateau', 'SECONDAIRE', 'La Malbaie', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École de la Rose-des-Vents', 'SECONDAIRE', 'L''Isle-aux-Coudres', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École régionale des Quatre-Saisons', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Boudreau', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Cardinal-Roy', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Joseph-François-Perrault', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire La Camaradière', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire de la Cité', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire de Neufchâtel', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire Roger-Comtois', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Jacques-Cartier - Saint-Denys-Garneau', 'SECONDAIRE', 'Sainte-Catherine-de-la-Jacques-Cartier', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire Vanier', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École L''Odyssée', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École des Pionniers', 'SECONDAIRE', 'Saint-Augustin-de-Desmaures', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Madeleine-Bergeron', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Saint-Michel', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire polyvalente de L''Ancienne-Lorette', 'SECONDAIRE', 'L''Ancienne-Lorette', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire De Rochebelle', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège des Compagnons', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Centre du Phénix', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Académie Sainte-Marie', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Samuel-De Champlain', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École de la Seigneurie', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École de la Relance', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École de l''Envol', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Polyvalente de Charlesbourg', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Joseph-Paquin', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École de la Courvilloise', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École du Mont-Sainte-Anne', 'SECONDAIRE', 'Beaupré', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Fierbourg, centre de formation professionnelle', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École du Phare', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Le Sommet', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École des Sentiers', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire de Donnacona', 'SECONDAIRE', 'Donnacona', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire Louis-Jobin', 'SECONDAIRE', 'Saint-Raymond', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire de Saint-Marc', 'SECONDAIRE', 'Saint-Marc-des-Carrières', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Avenues-Nouvelles', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École Marie-Leneuf', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire l''Escale', 'SECONDAIRE', 'Louiseville', 'Mauricie'),
  (gen_random_uuid(), 'Académie les Estacades', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire des Pionniers', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École Chavigny', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École le Tremplin', 'SECONDAIRE', 'Sainte-Geneviève-de-Batiscan', 'Mauricie'),
  (gen_random_uuid(), 'École des Boisés', 'SECONDAIRE', 'Saint-Alexis-des-Monts', 'Mauricie'),
  (gen_random_uuid(), 'École Notre-Dame-de-l''Assomption', 'SECONDAIRE', 'La Tuque', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire Val-Mauricie', 'SECONDAIRE', 'Shawinigan', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire des Chutes', 'SECONDAIRE', 'Shawinigan', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire Paul-Le Jeune', 'SECONDAIRE', 'Saint-Tite', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire du Rocher', 'SECONDAIRE', 'Shawinigan', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire Champagnat', 'SECONDAIRE', 'La Tuque', 'Mauricie'),
  (gen_random_uuid(), 'École de l''Énergie', 'SECONDAIRE', 'Shawinigan', 'Mauricie'),
  (gen_random_uuid(), 'École La Frontalière', 'SECONDAIRE', 'Coaticook', 'Estrie'),
  (gen_random_uuid(), 'Polyvalente Montignac', 'SECONDAIRE', 'Lac-Mégantic', 'Estrie'),
  (gen_random_uuid(), 'Polyvalente Louis-Saint-Laurent', 'SECONDAIRE', 'East Angus', 'Estrie'),
  (gen_random_uuid(), 'Maison familiale rurale du Granit', 'SECONDAIRE', 'Saint-Romain', 'Estrie'),
  (gen_random_uuid(), 'École des Enfants-de-la-Terre', 'SECONDAIRE', 'Waterville', 'Estrie'),
  (gen_random_uuid(), 'Centre hospitalier universitaire de Sherbrooke (Site Fleurimont)', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École du Triolet', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École de la Montée', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École Mitchell - Montcalm', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École internationale du Phare', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École du Touret', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École Le Monarque', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'Villa Marie-Claire', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École Le Goéland', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École secondaire de l''Escale', 'SECONDAIRE', 'Val-des-Sources', 'Estrie'),
  (gen_random_uuid(), 'École secondaire de la Ruche', 'SECONDAIRE', 'Magog', 'Estrie'),
  (gen_random_uuid(), 'École secondaire de l''Odyssée', 'SECONDAIRE', 'Valcourt', 'Estrie'),
  (gen_random_uuid(), 'École secondaire du Tournesol', 'SECONDAIRE', 'Windsor', 'Estrie'),
  (gen_random_uuid(), 'École Wiinibekuu School', 'SECONDAIRE', 'Waskaganish', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Wabannutao Eeyou School', 'SECONDAIRE', 'Eastmain', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Maquatua Eeyou School', 'SECONDAIRE', 'Wemindji', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École secondaire Mémoriale Voyageur', 'SECONDAIRE', 'Mistissini', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Badabin Eeyou School', 'SECONDAIRE', 'Whapmagoostui', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Mémoriale Willie J. Happyjack Memorial School', 'SECONDAIRE', 'Waswanipi', 'Nord-du-Québec'),
  (gen_random_uuid(), 'Ecole Big River High School', 'SECONDAIRE', 'Chisasibi', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Luke Mettaweskum School', 'SECONDAIRE', 'Nemaska', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Waapihtiiwewan School', 'SECONDAIRE', 'Oujé-Bougoumou', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Marc-Laflamme - Le Prélude', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Daniel-Johnson', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire de la Pointe-aux-Trembles', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Le Tournesol', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Antoine-de-Saint-Exupéry', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Irma-LeVasseur', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Guy-Vanier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Jean-Grou', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire La Passerelle', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire La Relance', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Amos', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Calixa-Lavallée', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire aux Mille-Voix', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Henri-Bourassa', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École FACE', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Dominique-Savio', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Hôpital Sainte-Justine', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École de la Lancée', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Irénée-Lussier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Joseph-Charbonneau', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Henri-Julien', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Centre Dollard-Cormier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'CHSLD Marie-Rollet', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Le Vitrail', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Louise-Trichet', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie Dunton', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Louis-Riel', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Marguerite-De Lajemmerais', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Chomedey-De Maisonneuve', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Eulalie-Durocher', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Joseph-François-Perrault', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Louis-Joseph-Papineau', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Pierre-Dupuy', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Jeanne-Mance', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie De Roberval', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Père-Marquette', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Georges-Vanier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Sophie-Barat', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Robert-Gravel', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Marie-Anne', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Lucien-Pagé', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École La Dauversière-Évangéline', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École internationale de Montréal', 'SECONDAIRE', 'Westmount', 'Montréal'),
  (gen_random_uuid(), 'École Saint-Henri', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Honoré-Mercier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École La Voie', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Saint-Luc', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École du Sas', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École du Sas', 'SECONDAIRE', 'Dorval', 'Montréal'),
  (gen_random_uuid(), 'École Mont-Royal', 'SECONDAIRE', 'Mont-Royal', 'Montréal'),
  (gen_random_uuid(), 'École Paul-Gérin-Lajoie-d''Outremont', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Pierre-Laporte', 'SECONDAIRE', 'Mont-Royal', 'Montréal')
ON CONFLICT (lower(name), coalesce(lower(city), '')) DO NOTHING;

INSERT INTO schools (id, name, type, city, region) VALUES
  (gen_random_uuid(), 'École Pierre-Laporte', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École de la Traversée', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Saint-Louis', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Cavelier-De LaSalle', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Dalbé-Viau', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Monseigneur-Richard', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Nouvelle école secondaire LaSalle', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École des Sources', 'SECONDAIRE', 'Dollard-des-Ormeaux', 'Montréal'),
  (gen_random_uuid(), 'École John-F.- Kennedy', 'SECONDAIRE', 'Beaconsfield', 'Montréal'),
  (gen_random_uuid(), 'École John-F.- Kennedy', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Rose-Virginie-Pelletier', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Félix-Leclerc', 'SECONDAIRE', 'Pointe-Claire', 'Montréal'),
  (gen_random_uuid(), 'École Dorval-Jean XXIII', 'SECONDAIRE', 'Dorval', 'Montréal'),
  (gen_random_uuid(), 'École Saint-Georges', 'SECONDAIRE', 'Senneville', 'Montréal'),
  (gen_random_uuid(), 'École de l''Altitude', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Ulluriaq', 'SECONDAIRE', 'Kangiqsualujjuaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Jaanimmarik', 'SECONDAIRE', 'Kuujjuaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Ajagutak', 'SECONDAIRE', 'Tasiujaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Tarsakallak', 'SECONDAIRE', 'Aupaluk', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Sautjuit', 'SECONDAIRE', 'Kangirsuk', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Isummasaqvik', 'SECONDAIRE', 'Quaqtaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Arsaniq', 'SECONDAIRE', 'Kangiqsujuaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Ikusik', 'SECONDAIRE', 'Salluit', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Nuvviti', 'SECONDAIRE', 'Ivujivik', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Iguarsivik', 'SECONDAIRE', 'Puvirnituq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Tukisiniarvik', 'SECONDAIRE', 'Akulivik', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Uquutaq', 'SECONDAIRE', 'Inukjuak', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Kiluutaq', 'SECONDAIRE', 'Umiujaq', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Asimauttaq', 'SECONDAIRE', 'Kuujjuarapik', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École du Nouveau-Monde', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Polyvalente Nicolas-Gatineau', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Polyvalente de l''Érablière', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'Polyvalente Le Carrefour', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire du Versant', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Euclide-Lanthier', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Saint-Jean-Bosco', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire de la Nouvelle-Ère', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire de la Cité', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire des Lacs', 'SECONDAIRE', 'La Pêche', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Grande-Rivière', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Mont-Bleu', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire de l''Île', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École des services spécialisés', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Providence/J.-M.-Robert', 'SECONDAIRE', 'Saint-André-Avellin', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Louis-Joseph-Papineau', 'SECONDAIRE', 'Papineauville', 'Outaouais'),
  (gen_random_uuid(), 'École Sainte-Famille/aux Trois-Chemins', 'SECONDAIRE', 'Thurso', 'Outaouais'),
  (gen_random_uuid(), 'École Saint-Michel', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Hormisdas-Gamelin', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Sieur-de-Coulonge', 'SECONDAIRE', 'Campbell''s Bay', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Sieur-de-Coulonge', 'SECONDAIRE', 'Mansfield-et-Pontefract', 'Outaouais'),
  (gen_random_uuid(), 'École du Coeur-de-la-Gatineau', 'SECONDAIRE', 'Gracefield', 'Outaouais'),
  (gen_random_uuid(), 'École de la Cité étudiante de la Haute-Gatineau', 'SECONDAIRE', 'Maniwaki', 'Outaouais'),
  (gen_random_uuid(), 'École Marcel-Raymond', 'SECONDAIRE', 'Lorrainville', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Gilbert-Théberge', 'SECONDAIRE', 'Témiscaming', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Rivière-des-Quinze', 'SECONDAIRE', 'Notre-Dame-du-Nord', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Du Carrefour', 'SECONDAIRE', 'Latulipe-et-Gaboury', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Sacré-Coeur', 'SECONDAIRE', 'Rouyn-Noranda', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École La Source', 'SECONDAIRE', 'Rouyn-Noranda', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École D''Iberville', 'SECONDAIRE', 'Rouyn-Noranda', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École de la Grande-Ourse', 'SECONDAIRE', 'Rouyn-Noranda', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire d''Amos', 'SECONDAIRE', 'Amos', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École de Barraute', 'SECONDAIRE', 'Barraute', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire Le Transit', 'SECONDAIRE', 'Val-d''Or', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire La Concorde', 'SECONDAIRE', 'Senneterre', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire La Concorde', 'SECONDAIRE', 'Val-d''Or', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire Le Tremplin', 'SECONDAIRE', 'Malartic', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire Le Tremplin', 'SECONDAIRE', 'Val-d''Or', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'Polyvalente Le Carrefour', 'SECONDAIRE', 'Val-d''Or', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Dagenais', 'SECONDAIRE', 'Palmarolle', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Boréale', 'SECONDAIRE', 'Normétal', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'Cité étudiante Polyno', 'SECONDAIRE', 'La Sarre', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École du Royal-Roussillon', 'SECONDAIRE', 'Macamic', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Notre-Dame-du-Sacré-Coeur', 'SECONDAIRE', 'Sacré-Coeur', 'Côte-Nord'),
  (gen_random_uuid(), 'École secondaire Serge-Bouchard', 'SECONDAIRE', 'Baie-Comeau', 'Côte-Nord'),
  (gen_random_uuid(), 'Polyvalente des Rivières', 'SECONDAIRE', 'Forestville', 'Côte-Nord'),
  (gen_random_uuid(), 'Polyvalente des Baies', 'SECONDAIRE', 'Baie-Comeau', 'Côte-Nord'),
  (gen_random_uuid(), 'Polyvalente des Berges', 'SECONDAIRE', 'Les Bergeronnes', 'Côte-Nord'),
  (gen_random_uuid(), 'École Saint-Luc', 'SECONDAIRE', 'Forestville', 'Côte-Nord'),
  (gen_random_uuid(), 'Polyvalente Horizon-Blanc', 'SECONDAIRE', 'Fermont', 'Côte-Nord'),
  (gen_random_uuid(), 'École Saint-Alexandre', 'SECONDAIRE', 'Port-Cartier', 'Côte-Nord'),
  (gen_random_uuid(), 'École Jacques-Cartier', 'SECONDAIRE', 'Sept-Îles', 'Côte-Nord'),
  (gen_random_uuid(), 'École Jean-du-Nord / Manikoutai', 'SECONDAIRE', 'Sept-Îles', 'Côte-Nord'),
  (gen_random_uuid(), 'Centre éducatif l''Abri', 'SECONDAIRE', 'Port-Cartier', 'Côte-Nord'),
  (gen_random_uuid(), 'École Monseigneur-Labrie', 'SECONDAIRE', 'Havre-Saint-Pierre', 'Côte-Nord'),
  (gen_random_uuid(), 'École Roger-Martineau', 'SECONDAIRE', 'Natashquan', 'Côte-Nord'),
  (gen_random_uuid(), 'École Hunault', 'SECONDAIRE', 'Rivière-au-Tonnerre', 'Côte-Nord'),
  (gen_random_uuid(), 'École des Riverains', 'SECONDAIRE', 'Longue-Pointe-de-Mingan', 'Côte-Nord'),
  (gen_random_uuid(), 'École La Porte-du-Nord', 'SECONDAIRE', 'Chibougamau', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Le Filon', 'SECONDAIRE', 'Chapais', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Le Delta', 'SECONDAIRE', 'Matagami', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Jacques-Rousseau', 'SECONDAIRE', 'Eeyou Istchee Baie-James', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École La Taïga', 'SECONDAIRE', 'Lebel-sur-Quévillon', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École Polyvalente des Îles', 'SECONDAIRE', 'Les Îles-de-la-Madeleine', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École de l''Escabelle - Saint-Norbert', 'SECONDAIRE', 'Cap-Chat', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École de Gabriel-Le Courtois', 'SECONDAIRE', 'Sainte-Anne-des-Monts', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Saint-Maxime', 'SECONDAIRE', 'Saint-Maxime-du-Mont-Louis', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École des Prospecteurs', 'SECONDAIRE', 'Murdochville', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Esdras-Minville', 'SECONDAIRE', 'Grande-Vallée', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Antoine-Roy', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École C.-E.-Pouliot', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire du Littoral', 'SECONDAIRE', 'Grande-Rivière', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École polyvalente Monseigneur Sévigny', 'SECONDAIRE', 'Chandler', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École polyvalente de Paspébiac', 'SECONDAIRE', 'Paspébiac', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École aux Quatre-Vents', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Le Bois-Vivant', 'SECONDAIRE', 'New Richmond', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Antoine-Bernard', 'SECONDAIRE', 'Carleton-sur-Mer', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École des Deux-Rivières', 'SECONDAIRE', 'Matapédia', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de Saint-Anselme', 'SECONDAIRE', 'Saint-Anselme', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de Saint-Charles', 'SECONDAIRE', 'Saint-Charles-de-Bellechasse', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Centre de formation en entreprise et récupération de Bellechasse', 'SECONDAIRE', 'Saint-Raphaël', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de Saint-Damien', 'SECONDAIRE', 'Saint-Damien-de-Buckland', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École de l''Envol', 'SECONDAIRE', 'Saint-Malachie', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Louis-Jacques-Casault', 'SECONDAIRE', 'Montmagny', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Bon-Pasteur', 'SECONDAIRE', 'L''Islet', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de Saint-Paul', 'SECONDAIRE', 'Saint-Paul-de-Montminy', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de la Rencontre', 'SECONDAIRE', 'Saint-Pamphile', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École Saint-Louis', 'SECONDAIRE', 'Thetford Mines', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente de Disraeli', 'SECONDAIRE', 'Disraeli', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente de Black Lake', 'SECONDAIRE', 'Thetford Mines', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente de Thetford Mines', 'SECONDAIRE', 'Thetford Mines', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Veilleux', 'SECONDAIRE', 'Saint-Joseph-de-Beauce', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente Saint-François', 'SECONDAIRE', 'Beauceville', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente de Saint-Georges', 'SECONDAIRE', 'Saint-Georges', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente des Abénaquis', 'SECONDAIRE', 'Saint-Prosper', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École des Appalaches', 'SECONDAIRE', 'Sainte-Justine', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente Benoît-Vachon', 'SECONDAIRE', 'Sainte-Marie', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École des Deux-Rives', 'SECONDAIRE', 'Saint-Georges', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Polyvalente Bélanger', 'SECONDAIRE', 'Saint-Martin', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École de la Clé-du-Boisé', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École de l''Îlot-des-Appalaches', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École Pointe-Lévy', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Champagnat, Guillaume-Couture', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire les Etchemins', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Centre de formation en entreprise et récupération', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de l''Horizon', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École de l''Envol', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire de l''Aubier', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École Beaurivage', 'SECONDAIRE', 'Saint-Agapit', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École Beaurivage', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Pamphile-Le May', 'SECONDAIRE', 'Sainte-Croix', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École secondaire Pamphile-Le May', 'SECONDAIRE', 'Lévis', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'École Poly-Jeunesse', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Curé-Antoine-Labelle', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Horizon Jeunesse', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École l''Odyssée-des-Jeunes', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Leblanc', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Georges-Vanier', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Alphonse-Desjardins', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'Centre de qualification professionnelle et d''entrepreneuriat de Laval', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Mont-de-La Salle', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Jean-Piaget', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Saint-Maxime', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Saint-Martin', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École de la Croisée', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École d''éducation internationale de Laval', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École de la Mosaïque', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École secondaire du Coteau', 'SECONDAIRE', 'Mascouche', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Jean-Baptiste-Meilleur', 'SECONDAIRE', 'Repentigny', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Paul-Arseneau', 'SECONDAIRE', 'L''Assomption', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire l''Horizon', 'SECONDAIRE', 'Repentigny', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Félix-Leclerc', 'SECONDAIRE', 'Repentigny', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de l''Amitié', 'SECONDAIRE', 'L''Assomption', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Jean-Claude-Crevier', 'SECONDAIRE', 'Repentigny', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire du Havre', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Le Prélude', 'SECONDAIRE', 'Mascouche', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Des Rives', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Armand-Corbeil', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire l''Impact', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de l''Odyssée', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire l''Envolée', 'SECONDAIRE', 'Mascouche', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire des Trois-Saisons', 'SECONDAIRE', 'Terrebonne', 'Lanaudière'),
  (gen_random_uuid(), 'École de programme intégré secondaire', 'SECONDAIRE', 'Repentigny', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire du Havre-Jeunesse', 'SECONDAIRE', 'Sainte-Julienne', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de la Rive', 'SECONDAIRE', 'Lavaltrie', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de l''Évolution', 'SECONDAIRE', 'Saint-Lin–Laurentides', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de l''Achigan', 'SECONDAIRE', 'Saint-Roch-de-l''Achigan', 'Lanaudière'),
  (gen_random_uuid(), 'École de l''Espace-Jeunesse', 'SECONDAIRE', 'Saint-Charles-Borromée', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Thérèse-Martin', 'SECONDAIRE', 'Joliette', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Pierre-de-Lestage', 'SECONDAIRE', 'Berthierville', 'Lanaudière'),
  (gen_random_uuid(), 'École Barthélemy-Joliette', 'SECONDAIRE', 'Joliette', 'Lanaudière'),
  (gen_random_uuid(), 'École Barthélemy-Joliette', 'SECONDAIRE', 'Saint-Charles-Borromée', 'Lanaudière'),
  (gen_random_uuid(), 'École Barthélemy-Joliette', 'SECONDAIRE', 'Saint-Thomas', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire des Montagnes', 'SECONDAIRE', 'Saint-Michel-des-Saints', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Bermon', 'SECONDAIRE', 'Saint-Gabriel-de-Brandon', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire des Chutes', 'SECONDAIRE', 'Rawdon', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire de l''Érablière', 'SECONDAIRE', 'Saint-Félix-de-Valois', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire d''Oka', 'SECONDAIRE', 'Oka', 'Laurentides'),
  (gen_random_uuid(), 'École Saint-Gabriel', 'SECONDAIRE', 'Sainte-Thérèse', 'Laurentides'),
  (gen_random_uuid(), 'Polyvalente Sainte-Thérèse', 'SECONDAIRE', 'Sainte-Thérèse', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Lucille-Teasdale', 'SECONDAIRE', 'Blainville', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Liberté-Jeunesse', 'SECONDAIRE', 'Sainte-Marthe-sur-le-Lac', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Henri-Dunant', 'SECONDAIRE', 'Blainville', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire du Maréchal', 'SECONDAIRE', 'Mirabel', 'Laurentides'),
  (gen_random_uuid(), 'Nouvelle école du Centre de réadaptation pour jeunes en difficultés d''adaptation de Sainte-Thérèse', 'SECONDAIRE', 'Sainte-Thérèse', 'Laurentides'),
  (gen_random_uuid(), 'École des Érables', 'SECONDAIRE', 'Deux-Montagnes', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire des Patriotes', 'SECONDAIRE', 'Saint-Eustache', 'Laurentides'),
  (gen_random_uuid(), 'Polyvalente Deux-Montagnes', 'SECONDAIRE', 'Deux-Montagnes', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Jean-Jacques-Rousseau', 'SECONDAIRE', 'Boisbriand', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire du Harfang', 'SECONDAIRE', 'Sainte-Anne-des-Plaines', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Rive-Nord', 'SECONDAIRE', 'Bois-des-Filion', 'Laurentides')
ON CONFLICT (lower(name), coalesce(lower(city), '')) DO NOTHING;

INSERT INTO schools (id, name, type, city, region) VALUES
  (gen_random_uuid(), 'École secondaire Hubert-Maisonneuve', 'SECONDAIRE', 'Rosemère', 'Laurentides'),
  (gen_random_uuid(), 'École des Hirondelles', 'SECONDAIRE', 'Saint-Eustache', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire du Flambeau', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Émilien-Frenette', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Saint-Stanislas', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Cap-Jeunesse', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École de l''Horizon-Soleil', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École Le Tremplin', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École Le Tremplin', 'SECONDAIRE', 'Sainte-Sophie', 'Laurentides'),
  (gen_random_uuid(), 'École Le Tremplin', 'SECONDAIRE', 'Prévost', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire des-Studios', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire des Hauts-Sommets', 'SECONDAIRE', 'Saint-Jérôme', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire de Mirabel', 'SECONDAIRE', 'Mirabel', 'Laurentides'),
  (gen_random_uuid(), 'École polyvalente Lavigne', 'SECONDAIRE', 'Lachute', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Curé-Mercure', 'SECONDAIRE', 'Mont-Tremblant', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Augustin-Norbert-Morin', 'SECONDAIRE', 'Sainte-Adèle', 'Laurentides'),
  (gen_random_uuid(), 'École Sacré-Coeur', 'SECONDAIRE', 'Saint-Donat', 'Lanaudière'),
  (gen_random_uuid(), 'Polyvalente des Monts', 'SECONDAIRE', 'Sainte-Agathe-des-Monts', 'Laurentides'),
  (gen_random_uuid(), 'École Vert-Pré', 'SECONDAIRE', 'Huberdeau', 'Laurentides'),
  (gen_random_uuid(), 'École Polyvalente Saint-Joseph', 'SECONDAIRE', 'Mont-Laurier', 'Laurentides'),
  (gen_random_uuid(), 'École du Méandre', 'SECONDAIRE', 'Rivière-Rouge', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Fernand-Lefebvre', 'SECONDAIRE', 'Sorel-Tracy', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Fernand-Lefebvre - Pavillon Tournesol', 'SECONDAIRE', 'Sorel-Tracy', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Bernard-Gariépy', 'SECONDAIRE', 'Sorel-Tracy', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Casavant', 'SECONDAIRE', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Fadette', 'SECONDAIRE', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'Polyvalente Hyacinthe-Delorme', 'SECONDAIRE', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'École Raymond', 'SECONDAIRE', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'École René-Saint-Pierre', 'SECONDAIRE', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'Polyvalente Robert-Ouimet', 'SECONDAIRE', 'Acton Vale', 'Montérégie'),
  (gen_random_uuid(), 'École Paul-Germain-Ostiguy', 'SECONDAIRE', 'Saint-Césaire', 'Montérégie'),
  (gen_random_uuid(), 'École Joséphine-Dandurand', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'École Marguerite-Bourgeoys', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'Polyvalente Marcel-Landry', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'Polyvalente Chanoine-Armand-Racicot', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'École Docteur-Alexis-Bouthillier', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'École Monseigneur-Euclide-Théberge', 'SECONDAIRE', 'Marieville', 'Montérégie'),
  (gen_random_uuid(), 'École Marie-Rivier', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'École spécialisée des Remparts', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Jacques-Ouellette', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École régionale du Vent-Nouveau', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Saint-Edmond', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École internationale Lucille-Teasdale', 'SECONDAIRE', 'Brossard', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire de l''Agora', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École André-Laurendeau', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Antoine-Brossard', 'SECONDAIRE', 'Brossard', 'Montérégie'),
  (gen_random_uuid(), 'École Gérard-Filion', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Jacques-Rousseau', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Monseigneur-A.-M.-Parent', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Saint-Jean-Baptiste', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Polybel', 'SECONDAIRE', 'Beloeil', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire De Mortagne', 'SECONDAIRE', 'Boucherville', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire le Tremplin', 'SECONDAIRE', 'Chambly', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire de Chambly', 'SECONDAIRE', 'Chambly', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire de Chambly', 'SECONDAIRE', 'Carignan', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Ozias-Leduc', 'SECONDAIRE', 'Beloeil', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Ozias-Leduc', 'SECONDAIRE', 'Mont-Saint-Hilaire', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire François-Williams', 'SECONDAIRE', 'Saint-Amable', 'Montérégie'),
  (gen_random_uuid(), 'École orientante l''Impact', 'SECONDAIRE', 'Boucherville', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire du Mont-Bruno', 'SECONDAIRE', 'Saint-Bruno-de-Montarville', 'Montérégie'),
  (gen_random_uuid(), 'École d''éducation internationale', 'SECONDAIRE', 'McMasterville', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire du Grand-Coteau', 'SECONDAIRE', 'Sainte-Julie', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire le Carrefour', 'SECONDAIRE', 'Varennes', 'Montérégie'),
  (gen_random_uuid(), 'École Monseigneur-Desranleau', 'SECONDAIRE', 'Bedford', 'Estrie'),
  (gen_random_uuid(), 'École l''Envolée', 'SECONDAIRE', 'Granby', 'Estrie'),
  (gen_random_uuid(), 'École de la Haute-Ville', 'SECONDAIRE', 'Granby', 'Estrie'),
  (gen_random_uuid(), 'École Joseph-Hermas-Leclerc', 'SECONDAIRE', 'Granby', 'Estrie'),
  (gen_random_uuid(), 'École Wilfrid-Léger', 'SECONDAIRE', 'Waterloo', 'Estrie'),
  (gen_random_uuid(), 'École Jean-Jacques-Bertrand', 'SECONDAIRE', 'Farnham', 'Estrie'),
  (gen_random_uuid(), 'École Massey-Vanier', 'SECONDAIRE', 'Cowansville', 'Estrie'),
  (gen_random_uuid(), 'École Saint-François-Xavier', 'SECONDAIRE', 'La Prairie', 'Montérégie'),
  (gen_random_uuid(), 'École de la Magdeleine', 'SECONDAIRE', 'La Prairie', 'Montérégie'),
  (gen_random_uuid(), 'École Fernand-Seguin', 'SECONDAIRE', 'Candiac', 'Montérégie'),
  (gen_random_uuid(), 'École des Timoniers', 'SECONDAIRE', 'Sainte-Catherine', 'Montérégie'),
  (gen_random_uuid(), 'École Jacques-Leber', 'SECONDAIRE', 'Saint-Constant', 'Montérégie'),
  (gen_random_uuid(), 'École Gabrielle-Roy', 'SECONDAIRE', 'Châteauguay', 'Montérégie'),
  (gen_random_uuid(), 'École Marguerite-Bourgeois', 'SECONDAIRE', 'Châteauguay', 'Montérégie'),
  (gen_random_uuid(), 'École Louis-Philippe-Paré', 'SECONDAIRE', 'Châteauguay', 'Montérégie'),
  (gen_random_uuid(), 'École régionale Brenda Milner', 'SECONDAIRE', 'Châteauguay', 'Montérégie'),
  (gen_random_uuid(), 'École Bonnier', 'SECONDAIRE', 'Mercier', 'Montérégie'),
  (gen_random_uuid(), 'École Pierre-Bédard', 'SECONDAIRE', 'Saint-Rémi', 'Montérégie'),
  (gen_random_uuid(), 'École Louis-Cyr', 'SECONDAIRE', 'Napierville', 'Montérégie'),
  (gen_random_uuid(), 'École du Tournant', 'SECONDAIRE', 'Saint-Constant', 'Montérégie'),
  (gen_random_uuid(), 'École du Parcours', 'SECONDAIRE', 'Salaberry-de-Valleyfield', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire des Patriotes-de-Beauharnois', 'SECONDAIRE', 'Beauharnois', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire des Patriotes-de-Beauharnois', 'SECONDAIRE', 'Salaberry-de-Valleyfield', 'Montérégie'),
  (gen_random_uuid(), 'École Sainte-Martine', 'SECONDAIRE', 'Sainte-Martine', 'Montérégie'),
  (gen_random_uuid(), 'École de la Baie-Saint-François', 'SECONDAIRE', 'Salaberry-de-Valleyfield', 'Montérégie'),
  (gen_random_uuid(), 'École Arthur-Pigeon', 'SECONDAIRE', 'Huntingdon', 'Montérégie'),
  (gen_random_uuid(), 'École Arthur-Pigeon', 'SECONDAIRE', 'Salaberry-de-Valleyfield', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Soulanges', 'SECONDAIRE', 'Saint-Polycarpe', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire de la Cité-des-Jeunes', 'SECONDAIRE', 'Vaudreuil-Dorion', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire du Chêne-Bleu', 'SECONDAIRE', 'Pincourt', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire des Navigateurs', 'SECONDAIRE', 'Saint-Zotique', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire des Échos', 'SECONDAIRE', 'Vaudreuil-Dorion', 'Montérégie'),
  (gen_random_uuid(), 'École Marquis', 'SECONDAIRE', 'Saint-Célestin', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire Jean-Nicolet', 'SECONDAIRE', 'Nicolet', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire la Découverte', 'SECONDAIRE', 'Saint-Léonard-d''Aston', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire les Seigneuries', 'SECONDAIRE', 'Saint-Pierre-les-Becquets', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École La Myriade J.-P.-H.-Massicotte', 'SECONDAIRE', 'Victoriaville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École de la Fermentière', 'SECONDAIRE', 'Warwick', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Prince-Daveluy', 'SECONDAIRE', 'Princeville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Notre-Dame-du-Perpétuel-Secours', 'SECONDAIRE', 'Ham-Nord', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire Monique-Proulx', 'SECONDAIRE', 'Warwick', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire Le tandem Albert-Morissette', 'SECONDAIRE', 'Victoriaville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire Le boisé', 'SECONDAIRE', 'Victoriaville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Polyvalente La Samare', 'SECONDAIRE', 'Plessisville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Sainte-Marie', 'SECONDAIRE', 'Princeville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Sainte-Anne', 'SECONDAIRE', 'Daveluyville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'Centre de formation en entreprise et en récupération Normand-Maurice', 'SECONDAIRE', 'Victoriaville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Duvernay - Chabanel', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Saint-Pie X', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Jean-Raimbault', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Jeanne-Mance', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École Marie-Rivier', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École La Poudrière', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École du Bosquet', 'SECONDAIRE', 'Drummondville', 'Centre-du-Québec'),
  (gen_random_uuid(), 'École secondaire Québec High School', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École Dollard-des-Ormeaux', 'SECONDAIRE', 'Shannon', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire Saint-Patrick', 'SECONDAIRE', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'École secondaire A.S. Johnson Memorial', 'SECONDAIRE', 'Thetford Mines', 'Chaudière-Appalaches'),
  (gen_random_uuid(), 'Académie de Trois-Rivières', 'SECONDAIRE', 'Trois-Rivières', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire de La Tuque', 'SECONDAIRE', 'La Tuque', 'Mauricie'),
  (gen_random_uuid(), 'École secondaire régionale Riverside', 'SECONDAIRE', 'Saguenay', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'École MacLean Memorial', 'SECONDAIRE', 'Chibougamau', 'Nord-du-Québec'),
  (gen_random_uuid(), 'École secondaire de New Carlisle', 'SECONDAIRE', 'New Carlisle', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de New Carlisle', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de New Carlisle', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École de Métis-sur-Mer', 'SECONDAIRE', 'Métis-sur-Mer', 'Bas-Saint-Laurent'),
  (gen_random_uuid(), 'Polyvalente de Gaspé', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'Polyvalente de Gaspé', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de Grosse-Îles', 'SECONDAIRE', 'Grosse-Île', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire Evergreen', 'SECONDAIRE', 'Chandler', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire Evergreen', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire Evergreen', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de New Richmond', 'SECONDAIRE', 'New Richmond', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de New Richmond', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire de New Richmond', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Intermédiaire d''Escuminac', 'SECONDAIRE', 'Escuminac', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Intermédiaire d''Escuminac', 'SECONDAIRE', 'Gaspé', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École Intermédiaire d''Escuminac', 'SECONDAIRE', 'Bonaventure', 'Gaspésie–Îles-de-la-Madeleine'),
  (gen_random_uuid(), 'École secondaire Queen Elizabeth', 'SECONDAIRE', 'Sept-Îles', 'Côte-Nord'),
  (gen_random_uuid(), 'École primaire Butler', 'SECONDAIRE', 'Bedford', 'Estrie'),
  (gen_random_uuid(), 'École primaire Heroes'' Memorial', 'SECONDAIRE', 'Cowansville', 'Estrie'),
  (gen_random_uuid(), 'Académie Knowlton', 'SECONDAIRE', 'Lac-Brome', 'Estrie'),
  (gen_random_uuid(), 'École primaire de Mansonville', 'SECONDAIRE', 'Potton', 'Estrie'),
  (gen_random_uuid(), 'École primaire de Waterloo', 'SECONDAIRE', 'Waterloo', 'Estrie'),
  (gen_random_uuid(), 'École secondaire régionale Alexander Galt', 'SECONDAIRE', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'École secondaire régionale de Richmond', 'SECONDAIRE', 'Richmond', 'Estrie'),
  (gen_random_uuid(), 'École Saint-Johns', 'SECONDAIRE', 'Saint-Jean-sur-Richelieu', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire régionale Héritage', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École Reach', 'SECONDAIRE', 'Saint-Lambert', 'Montérégie'),
  (gen_random_uuid(), 'École Reach', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire internationale de Saint-Lambert', 'SECONDAIRE', 'Saint-Lambert', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire régionale Centennial', 'SECONDAIRE', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'Centre de la Nature et des Sciences d''Arundel', 'SECONDAIRE', 'Arundel', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire de Joliette', 'SECONDAIRE', 'Joliette', 'Lanaudière'),
  (gen_random_uuid(), 'École secondaire Lake of Two Mountains', 'SECONDAIRE', 'Deux-Montagnes', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire régionale Laurentian', 'SECONDAIRE', 'Lachute', 'Laurentides'),
  (gen_random_uuid(), 'École alternative Phoenix', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École secondaire de Rosemère', 'SECONDAIRE', 'Rosemère', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Laval Junior', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'Académie de Sainte-Agathe', 'SECONDAIRE', 'Sainte-Agathe-des-Monts', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Laval Senior', 'SECONDAIRE', 'Laval', 'Laval'),
  (gen_random_uuid(), 'École Secondaire Mountainview', 'SECONDAIRE', 'Prévost', 'Laurentides'),
  (gen_random_uuid(), 'École secondaire Philemon Wright', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire Pontiac', 'SECONDAIRE', 'Shawville', 'Outaouais'),
  (gen_random_uuid(), 'École secondaire D''Arcy McGee', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Dr. Wilbert Keon', 'SECONDAIRE', 'L''Isle-aux-Allumettes', 'Outaouais'),
  (gen_random_uuid(), 'École Golden Valley', 'SECONDAIRE', 'Val-d''Or', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Namur', 'SECONDAIRE', 'Namur', 'Outaouais'),
  (gen_random_uuid(), 'École Noranda', 'SECONDAIRE', 'Rouyn-Noranda', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École secondaire Saint-Michael', 'SECONDAIRE', 'Low', 'Outaouais'),
  (gen_random_uuid(), 'École Intermédiaire Hadley', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'Centre de Réadaptation les jeunes de l''Outaouais', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École Intermédiaire Symmes', 'SECONDAIRE', 'Gatineau', 'Outaouais'),
  (gen_random_uuid(), 'École primaire Maniwaki Woodland', 'SECONDAIRE', 'Maniwaki', 'Outaouais'),
  (gen_random_uuid(), 'École G. Théberge', 'SECONDAIRE', 'Témiscaming', 'Abitibi-Témiscamingue'),
  (gen_random_uuid(), 'École Saint-Raphaël', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Royal Vale', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École F.A.C.E.', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire James Lyng', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie LaurenHill', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Laurier Macdonald', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Lester B. Pearson', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire M.I.N.D.', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie Internationale Marymount', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire L.I.N.K.S.', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie Royal West', 'SECONDAIRE', 'Montréal-Ouest', 'Montréal'),
  (gen_random_uuid(), 'Collège Vincent Massey', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Westmount', 'SECONDAIRE', 'Westmount', 'Montréal'),
  (gen_random_uuid(), 'École secondaire John Grant', 'SECONDAIRE', 'Côte-Saint-Luc', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Options', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Outreach', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Programme Mile-End', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Venture', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Vézina', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Ecole secondaire Perspectives I', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Ecole secondaire Perspectives II', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Hôpital pour enfants Shriners', 'SECONDAIRE', 'Montréal', 'Montréal')
ON CONFLICT (lower(name), coalesce(lower(city), '')) DO NOTHING;

INSERT INTO schools (id, name, type, city, region) VALUES
  (gen_random_uuid(), 'Centre de réadaption Marie-Enfant - CHU Saint-Justine', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Unité Ulluriaq Boys', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cité des Prairies', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Elizabeth', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Centre Mackay', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Centre Mackay', 'SECONDAIRE', 'Westmount', 'Montréal'),
  (gen_random_uuid(), 'Hôpital de Montréal pour enfants', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Centre Mountainview School Project', 'SECONDAIRE', 'Côte-Saint-Luc', 'Montréal'),
  (gen_random_uuid(), 'Centre Mountainview School Project', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Philip E. Layton', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Sir Mortimer B. Davis', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Focus', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Académie Québec Virtual', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Beaconsfield', 'SECONDAIRE', 'Beaconsfield', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Westwood Senior', 'SECONDAIRE', 'Hudson', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire John-Rennie', 'SECONDAIRE', 'Pointe-Claire', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Lakeside Academy', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Macdonald', 'SECONDAIRE', 'Sainte-Anne-de-Bellevue', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Pierrefonds', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Saint-Thomas', 'SECONDAIRE', 'Pointe-Claire', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Westwood Junior', 'SECONDAIRE', 'Saint-Lazare', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire Beurling Academy', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École Angrignon', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Centre d''accueil Dawson Alternative', 'SECONDAIRE', 'Beaconsfield', 'Montréal'),
  (gen_random_uuid(), 'Centre d''accueil Dawson Alternative', 'SECONDAIRE', 'Dorval', 'Montréal'),
  (gen_random_uuid(), 'Centre Bourbonnière (Mountainview)', 'SECONDAIRE', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Centre d''accueil le Programme de Portage inc.', 'SECONDAIRE', 'Beaconsfield', 'Montréal'),
  (gen_random_uuid(), 'École secondaire Horizon', 'SECONDAIRE', 'Pointe-Claire', 'Montréal'),
  (gen_random_uuid(), 'École secondaire régionale Châteauguay Valley', 'SECONDAIRE', 'Ormstown', 'Montérégie'),
  (gen_random_uuid(), 'École secondaire régionale Howard S. Billings', 'SECONDAIRE', 'Châteauguay', 'Montérégie'),
  (gen_random_uuid(), 'L''Académie Beth Rivkah pour filles', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie François-Labelle', 'SECONDAIRE', 'Repentigny', NULL),
  (gen_random_uuid(), 'Académie Kells', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie Kuper', 'SECONDAIRE', 'Kirkland', NULL),
  (gen_random_uuid(), 'Académie Lafontaine inc.', 'SECONDAIRE', 'Saint-Jérôme', NULL),
  (gen_random_uuid(), 'Académie Louis-Pasteur', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie Marie-Claire', 'SECONDAIRE', 'Kirkland', NULL),
  (gen_random_uuid(), 'Académie Solomon Schechter', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Aviron Québec Collège Technique', 'SECONDAIRE', 'Québec', NULL),
  (gen_random_uuid(), 'Collège Charlemagne inc.', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Charles-Lemoyne', 'SECONDAIRE', 'Longueuil', NULL),
  (gen_random_uuid(), 'Collège de l''Ouest de l''Île', 'SECONDAIRE', 'Dollard-des-Ormeaux', NULL),
  (gen_random_uuid(), 'Collège Supérieur de Montréal', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Jésus-Marie de Bellechasse', 'SECONDAIRE', 'Saint-Michel-de-Bellechasse', NULL),
  (gen_random_uuid(), 'Collège Français', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Français', 'SECONDAIRE', 'Longueuil', NULL),
  (gen_random_uuid(), 'Collège Héritage de Châteauguay inc.', 'SECONDAIRE', 'Châteauguay', NULL),
  (gen_random_uuid(), 'Collège Prep International', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Saint-Alexandre de la Gatineau', 'SECONDAIRE', 'Gatineau', NULL),
  (gen_random_uuid(), 'Cestar Collège, Campus Longueuil', 'SECONDAIRE', 'Longueuil', NULL),
  (gen_random_uuid(), 'Académie internationale Zig Zag', 'SECONDAIRE', 'Victoriaville', NULL),
  (gen_random_uuid(), 'Collège Supérieur de Sherbrooke', 'SECONDAIRE', 'Sherbrooke', NULL),
  (gen_random_uuid(), 'École secondaire Duval inc.', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Boisbriand 2016', 'SECONDAIRE', 'Boisbriand', NULL),
  (gen_random_uuid(), 'École secondaire Saint-Joseph de Saint-Hyacinthe', 'SECONDAIRE', 'Saint-Hyacinthe', NULL),
  (gen_random_uuid(), 'Académie adventiste Greaves', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'L''Académie Centennial', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie hébraïque inc.', 'SECONDAIRE', 'Côte-Saint-Luc', NULL),
  (gen_random_uuid(), 'La Petite Académie', 'SECONDAIRE', 'Saint-Hyacinthe', NULL),
  (gen_random_uuid(), 'Séminaire Marie-Reine-du-Clergé', 'SECONDAIRE', 'Métabetchouan–Lac-à-la-Croix', NULL),
  (gen_random_uuid(), 'Le Collège Lower Canada', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie des Sacrés-Coeurs', 'SECONDAIRE', 'Saint-Bruno-de-Montarville', NULL),
  (gen_random_uuid(), 'Séminaire de Chicoutimi - services éducatifs', 'SECONDAIRE', 'Saguenay', NULL),
  (gen_random_uuid(), 'Séminaire du Sacré Coeur', 'SECONDAIRE', 'Grenville-sur-la-Rouge', NULL),
  (gen_random_uuid(), 'Le Séminaire Sainte-Marie', 'SECONDAIRE', 'Shawinigan', NULL),
  (gen_random_uuid(), 'Collège Trafalgar pour filles', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie Yéshiva Yavné', 'SECONDAIRE', 'Côte-Saint-Luc', NULL),
  (gen_random_uuid(), 'Collège Jacques-Prévert', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie des pompiers', 'SECONDAIRE', 'Mirabel', NULL),
  (gen_random_uuid(), 'Collège CDI Administration. Technologie. Santé', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Herzing', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie St-Margaret', 'SECONDAIRE', 'Mascouche', NULL),
  (gen_random_uuid(), 'Académie Trivium', 'SECONDAIRE', 'Gatineau', NULL),
  (gen_random_uuid(), 'Académie Juillet', 'SECONDAIRE', 'Candiac', NULL),
  (gen_random_uuid(), 'Église-École Académie chrétienne de la Foi', 'SECONDAIRE', 'Vaudreuil-Dorion', NULL),
  (gen_random_uuid(), 'Académie Lavalloise', 'SECONDAIRE', 'Laval', NULL),
  (gen_random_uuid(), 'Académie Étoile du Nord Laval', 'SECONDAIRE', 'Laval', NULL),
  (gen_random_uuid(), 'Collège Milestone', 'SECONDAIRE', 'Brossard', NULL),
  (gen_random_uuid(), 'Collège St-Michel', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège de technologie Veritas inc.', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Canada', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Académie Nour', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Greystone', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège April-Fortier', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège Royal du Québec', 'SECONDAIRE', 'Montréal', NULL),
  (gen_random_uuid(), 'Collège l''Avenir de Rosemont inc.', 'SECONDAIRE', 'Montréal', NULL)
ON CONFLICT (lower(name), coalesce(lower(city), '')) DO NOTHING;

-- New CEGEP schools (45 rows)
INSERT INTO schools (id, name, type, city, region) VALUES
  (gen_random_uuid(), 'Campus Notre-Dame-de-Foy', 'CEGEP', 'Saint-Augustin-de-Desmaures', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège Royal du Québec', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Mérici Collégial Privé', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège Bart (1975)', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège O''Sullivan de Québec inc.', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège TAV', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Décarie', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collégial international Sainte-Anne', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Canada', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège St-Michel, Pavillon Sauvé', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège des Technologies de l''Information de Montréal', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège de gestion, technologie et santé Matrix inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Avalon', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Collège Greystone', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'École de management INSA', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège l''Avenir de Rosemont inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Cumberland', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège national de science et technologie inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Kensley inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège de Technologie Ascent inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Institut Élite de Montréal', 'CEGEP', 'Longueuil', 'Montérégie'),
  (gen_random_uuid(), 'Collège Milestone', 'CEGEP', 'Brossard', 'Montérégie'),
  (gen_random_uuid(), 'École Supérieure Internationale de Montréal', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Stanislas inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège O''Sullivan de Montréal inc.', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège April-Fortier', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Herzing', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Les Écoles Créatives', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Collège Unica', 'CEGEP', 'Westmount', 'Montréal'),
  (gen_random_uuid(), 'Cégep de St-Hyacinthe', 'CEGEP', 'Saint-Hyacinthe', 'Montérégie'),
  (gen_random_uuid(), 'Cégep régional de Lanaudière à Joliette', 'CEGEP', 'Joliette', 'Lanaudière'),
  (gen_random_uuid(), 'Cégep à distance', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cégep à distance international', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cégep à distance (anglophone)', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cégep François-Xavier Garneau', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Cégep André-Laurendeau', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cégep de St-Félicien', 'CEGEP', 'Saint-Félicien', 'Saguenay–Lac-Saint-Jean'),
  (gen_random_uuid(), 'Collège Dawson', 'CEGEP', 'Montréal', 'Montréal'),
  (gen_random_uuid(), 'Cégep John Abbott', 'CEGEP', 'Sainte-Anne-de-Bellevue', 'Montréal'),
  (gen_random_uuid(), 'Cégep régional Champlain', 'CEGEP', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'Cégep Champlain à Lennoxville', 'CEGEP', 'Sherbrooke', 'Estrie'),
  (gen_random_uuid(), 'Cégep Champlain-Saint-Lawrence', 'CEGEP', 'Québec', 'Capitale-Nationale'),
  (gen_random_uuid(), 'Cégep Champlain à Saint-Lambert', 'CEGEP', 'Saint-Lambert', 'Montérégie'),
  (gen_random_uuid(), 'Cégep régional de Lanaudière à L''Assomption', 'CEGEP', 'L''Assomption', 'Lanaudière'),
  (gen_random_uuid(), 'Cégep régional de Lanaudière à Terrebonne', 'CEGEP', 'Terrebonne', 'Lanaudière')
ON CONFLICT (lower(name), coalesce(lower(city), '')) DO NOTHING;

-- Backfill city/region on existing rows (67 rows)
UPDATE schools SET city = 'Matane', region = 'Bas-Saint-Laurent' WHERE id = '53428e56-7850-49b2-a110-b8c5540bae28' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Rivière-du-Loup', region = 'Bas-Saint-Laurent' WHERE id = '52e99123-379b-40cc-b3df-4bb05b7db5ce' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saguenay', region = 'Saguenay–Lac-Saint-Jean' WHERE id = '1031135c-56eb-4ce9-8bc0-01a42b7707f4' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Québec', region = 'Capitale-Nationale' WHERE id = '53c3d88d-452a-4e2e-8e4d-aeab3b6b14a5' AND (city IS NULL OR region IS NULL);
UPDATE schools SET region = 'Montréal' WHERE id = '1f32b1be-3ecf-45f1-89aa-87883256711b' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '197886cf-3948-4c69-afa8-0d24de26c37f' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '90d2fe15-c4ce-4340-8c94-394f5fd15233' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saint-Jérôme', region = 'Laurentides' WHERE id = '20d2b5d3-0916-4fd0-b645-1b604a3c4877' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Shawinigan', region = 'Mauricie' WHERE id = '613aaadc-0947-43fa-8f89-84f73fdaf8b0' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Baie-Comeau', region = 'Côte-Nord' WHERE id = 'a262966a-6210-4c13-8c76-7edfc288b31e' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = 'e9276c29-1aee-4bee-a5fc-8a5a9e554f37' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '2e9fa603-0f2a-412a-98c7-a44e051402db' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'L''Assomption' WHERE id = '64d62dd8-0a96-4f23-9ee7-b6fdc735fcde' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal' WHERE id = '53c3d88d-452a-4e2e-8e4d-aeab3b6b14a5' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal' WHERE id = 'd114a436-9245-4b69-86fb-78b1243b209d' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Laval' WHERE id = '6a8693b4-a7cc-4c07-97f5-f8d214ce99ce' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sherbrooke' WHERE id = '7adaa8e9-015b-4d5b-869e-3646d072935a' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Drummondville', region = 'Centre-du-Québec' WHERE id = 'ee66dfcd-6e4d-49a9-ad9f-aa2fa50efcaa' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Trois-Rivières', region = 'Mauricie' WHERE id = 'c900fdce-f25b-4d03-8915-ceffc75d62c3' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sherbrooke', region = 'Estrie' WHERE id = '7adaa8e9-015b-4d5b-869e-3646d072935a' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Gatineau', region = 'Outaouais' WHERE id = '2b337acb-cb0a-4ad0-ab71-aecaf1cf6d96' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '05841265-fd61-466e-b431-2caa7ec06de9' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '2e9fa603-0f2a-412a-98c7-a44e051402db' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '53c3d88d-452a-4e2e-8e4d-aeab3b6b14a5' AND (city IS NULL OR region IS NULL);
UPDATE schools SET region = 'Montréal' WHERE id = '6d36b5dd-fbb2-430b-a55f-a3eae0b782ab' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Westmount', region = 'Montréal' WHERE id = 'c0b63557-8768-44cd-b9d6-2160ab90a6cb' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Gaspé', region = 'Gaspésie–Îles-de-la-Madeleine' WHERE id = '1c6a15bb-7245-4308-a785-a3a46454951c' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Rimouski', region = 'Bas-Saint-Laurent' WHERE id = '3ab3f7ad-4396-4c57-b823-27c8b105d2b0' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Québec', region = 'Capitale-Nationale' WHERE id = '03bd95e3-3c3c-4161-ae63-5b0678545a66' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Québec', region = 'Capitale-Nationale' WHERE id = '9bff70c3-f656-44e7-9566-79355ea716bd' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sherbrooke', region = 'Estrie' WHERE id = '8a330cf7-76fa-4761-8cbd-df223e6c4cbd' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Granby', region = 'Estrie' WHERE id = '98332099-2968-4b11-83ac-fdfe064d3079' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Trois-Rivières', region = 'Mauricie' WHERE id = '61ed3f9a-f089-4983-87e9-85bab65e1693' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Shawinigan', region = 'Mauricie' WHERE id = '613aaadc-0947-43fa-8f89-84f73fdaf8b0' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Drummondville', region = 'Centre-du-Québec' WHERE id = '3cfd174c-95fe-4b82-b96c-61a045e8e5d9' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sorel-Tracy', region = 'Montérégie' WHERE id = '55f424c0-d740-43e5-99f6-38a8fb73e03b' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saint-Jean-sur-Richelieu', region = 'Montérégie' WHERE id = 'f09a5ec6-20af-465c-a97a-0d71d8c8b291' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Longueuil', region = 'Montérégie' WHERE id = '197886cf-3948-4c69-afa8-0d24de26c37f' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sainte-Thérèse', region = 'Laurentides' WHERE id = 'f7fafd77-a20b-4f96-8db5-afb999e7e4d9' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '90d2fe15-c4ce-4340-8c94-394f5fd15233' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = 'f6ffbe4c-8d82-411a-8188-8b8256816ec6' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '38b003b6-be02-4f7a-a548-d26e103f7e97' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = 'e9276c29-1aee-4bee-a5fc-8a5a9e554f37' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = 'af3e3ada-eadb-41ff-8d9f-2f34dd149317' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '2ecca369-433b-402d-9c35-3eaba59e0563' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Salaberry-de-Valleyfield', region = 'Montérégie' WHERE id = '24c038d8-0a12-4516-8404-bca92543cb6a' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Gatineau', region = 'Outaouais' WHERE id = '103c0ac1-9e07-4341-a5a2-af799d0879a8' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Gatineau', region = 'Outaouais' WHERE id = '4bbf7b50-684b-4f21-9def-e5511c3b3533' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Rouyn-Noranda', region = 'Abitibi-Témiscamingue' WHERE id = 'e55589cc-4ac2-409e-bcab-60bd531f8186' AND (city IS NULL OR region IS NULL);
UPDATE schools SET region = 'Chaudière-Appalaches' WHERE id = '3f45cb94-5625-4d9a-91db-06bc5d2aa574' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Rivière-du-Loup', region = 'Bas-Saint-Laurent' WHERE id = '52e99123-379b-40cc-b3df-4bb05b7db5ce' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'La Pocatière', region = 'Bas-Saint-Laurent' WHERE id = '4927bfc9-4003-4ce3-ba80-df53343d15ad' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Thetford Mines', region = 'Chaudière-Appalaches' WHERE id = '55925e8f-3575-4c5b-8b4c-7a018e3cee7e' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Victoriaville', region = 'Centre-du-Québec' WHERE id = 'e8c0094e-10c1-43d5-810b-e8048a5c2e87' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Matane', region = 'Bas-Saint-Laurent' WHERE id = '53428e56-7850-49b2-a110-b8c5540bae28' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saint-Jérôme', region = 'Laurentides' WHERE id = '20d2b5d3-0916-4fd0-b645-1b604a3c4877' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Laval', region = 'Laval' WHERE id = 'ee2d611c-d140-417c-bbaf-d6353a7a1229' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Baie-Comeau', region = 'Côte-Nord' WHERE id = 'a262966a-6210-4c13-8c76-7edfc288b31e' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Sept-Îles', region = 'Côte-Nord' WHERE id = 'e9aed637-e75d-4393-89c9-649498cea8b1' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Alma', region = 'Saguenay–Lac-Saint-Jean' WHERE id = 'fda8a4a6-5a48-4a75-8d6e-fb8140dc419a' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saguenay', region = 'Saguenay–Lac-Saint-Jean' WHERE id = '039bb660-34c4-4065-af23-63437d1fcbba' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saguenay', region = 'Saguenay–Lac-Saint-Jean' WHERE id = '1031135c-56eb-4ce9-8bc0-01a42b7707f4' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '968ed36e-bca7-45d0-b63e-3b41ba385f6b' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Saint-Georges', region = 'Chaudière-Appalaches' WHERE id = 'eab74df7-0aa6-438d-b5d8-2bcca8f6048a' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = '35ed7851-535d-4620-8673-13e71a7c3dc3' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Montréal', region = 'Montréal' WHERE id = 'd49956fe-488a-4caa-9428-6de29f2cb5a1' AND (city IS NULL OR region IS NULL);
UPDATE schools SET city = 'Repentigny', region = 'Lanaudière' WHERE id = '40c3f945-7ff3-4102-85d9-7f30cc0a6301' AND (city IS NULL OR region IS NULL);

COMMIT;